# This file was generated by GoReleaser. DO NOT EDIT.
cask "goenv" do
  name "goenv"
  desc "TUI for viewing and editing Go environment variables"
  homepage "https://github.com/alexrios/goenv"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goenv"

  on_macos do
    on_intel do
      url "https://github.com/alexrios/goenv/releases/download/v#{version}/goenv_#{version}_darwin_amd64.tar.gz"
      sha256 "24c2a8ab35a5785687da35784d84a21b5e772468a6243c33edf3cbc98929537d"
    end
    on_arm do
      url "https://github.com/alexrios/goenv/releases/download/v#{version}/goenv_#{version}_darwin_arm64.tar.gz"
      sha256 "abd82c853f6f7908607fac23e04076190c2183d8108d6d10f5531bed309f97b9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/alexrios/goenv/releases/download/v#{version}/goenv_#{version}_linux_amd64.tar.gz"
      sha256 "1ecab6b865bce98acb5d4c59d59209a45bcae4b42caa70f15f0ee8987a5bf21e"
    end
    on_arm do
      url "https://github.com/alexrios/goenv/releases/download/v#{version}/goenv_#{version}_linux_arm64.tar.gz"
      sha256 "82dea02fdb2e0eddebaea8a55f9a2e9d260da8977bbd6d3b0cf007e01e9a16ae"
    end
  end

  # No zap stanza required
end
