# This file was generated by GoReleaser. DO NOT EDIT.
cask "goenv" do
  name "goenv"
  desc "TUI for viewing and editing Go environment variables"
  homepage "https://github.com/alexrios/goenv"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goenv"

  on_macos do
    on_intel do
      url "https://github.com/alexrios/goenv/releases/download/v#{version}/goenv_#{version}_darwin_amd64.tar.gz"
      sha256 "294203e441f7190907bf3d51328874997bd389e59a1fbf3a4e85bda0b510e825"
    end
    on_arm do
      url "https://github.com/alexrios/goenv/releases/download/v#{version}/goenv_#{version}_darwin_arm64.tar.gz"
      sha256 "7b1cedb91994b4d7b67d40a89a1ca189551a0bac24cdf66dc31cc390d6e796ec"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/alexrios/goenv/releases/download/v#{version}/goenv_#{version}_linux_amd64.tar.gz"
      sha256 "c8b077eca67ba7bc65848b4651a8031bc8928dd23b8cea080c1fa61c6a4932ee"
    end
    on_arm do
      url "https://github.com/alexrios/goenv/releases/download/v#{version}/goenv_#{version}_linux_arm64.tar.gz"
      sha256 "2736ed76d0339e88641602d164cfdb5bac13bc975039a4211c00a322236790f5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/goenv"]
    end
  end

  # No zap stanza required
end
