# This file was generated by GoReleaser. DO NOT EDIT.
cask "goenv" do
  name "goenv"
  desc "TUI for viewing and editing Go environment variables"
  homepage "https://github.com/alexrios/goenv"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goenv"

  on_macos do
    on_intel do
      url "https://github.com/alexrios/goenv/releases/download/v#{version}/goenv_#{version}_darwin_amd64.tar.gz"
      sha256 "8e23470d8862602839c8b93859325212ec06c7ec4d555036c0f13be91c6f10c5"
    end
    on_arm do
      url "https://github.com/alexrios/goenv/releases/download/v#{version}/goenv_#{version}_darwin_arm64.tar.gz"
      sha256 "406b54d59f7752b3ab769461ab7eff6b572ddea26650e1e4684a2da08506c092"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/alexrios/goenv/releases/download/v#{version}/goenv_#{version}_linux_amd64.tar.gz"
      sha256 "42879f9b839a0a047efa9acf60ddbe6e9c1b6820db196e1fa5c225387ecffbe0"
    end
    on_arm do
      url "https://github.com/alexrios/goenv/releases/download/v#{version}/goenv_#{version}_linux_arm64.tar.gz"
      sha256 "de008e1ff7fadb18f0a4e5f139050ccbba7c1f44c7b424fd41f455d97eea230c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/goenv"]
    end
  end

  # No zap stanza required
end
