# This file was generated by GoReleaser. DO NOT EDIT.
cask "halo" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "3e4c603a578f87c78524a75b65f647c1f6611a9a988fea7bef095c71c0291e21"
      url "https://github.com/alexrios/halo/releases/download/v#{version}/halo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7e6bc111cf8ff7145df171d0a9da00bdfe928df8717c0b80c319c7999bb63a14"
      url "https://github.com/alexrios/halo/releases/download/v#{version}/halo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0a4c9dab31349558b131d834e149eb3c2b77dcf30141ae055ba73e11391539ec"
      url "https://github.com/alexrios/halo/releases/download/v#{version}/halo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f48fb13dc2c72dd4e73b609205549d05b56d4496e5bcc278ce75159fb20727e4"
      url "https://github.com/alexrios/halo/releases/download/v#{version}/halo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "halo"
  desc "Invisible AI context for Claude Code"
  homepage "https://github.com/alexrios/halo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "halo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/halo"]
    end
  end

  # No zap stanza required

end
