# This file was generated by GoReleaser. DO NOT EDIT.
cask "opq" do
  version "1.2.1"

  on_macos do
    on_intel do
      sha256 "f4fd84a55e32099fdba550be9ddebbb542d92b56aca11cf78c8b1b81a8cc08cf"
      url "https://github.com/alexrios/opq/releases/download/v#{version}/opq_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d919866422760a5990c4e69b2cfaf5c69459439ce7e820e13fb675b6a6e26f3f"
      url "https://github.com/alexrios/opq/releases/download/v#{version}/opq_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c6fdcd10e7767a8a0dc58ee466acd8e31808a2c5434a9c3a1f7ffa976bf9f1f0"
      url "https://github.com/alexrios/opq/releases/download/v#{version}/opq_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1159e88c794a33a5f701874909da4161d77e8455d28c8318ac551ce4725db685"
      url "https://github.com/alexrios/opq/releases/download/v#{version}/opq_#{version}_linux_arm64.tar.gz"
    end
  end

  name "opq"
  desc "AI-safe secrets CLI that keeps plaintext from callers and AI agents"
  homepage "https://github.com/alexrios/opq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opq"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/opq"]
    end
  end

  # No zap stanza required

end
