# This file was generated by GoReleaser. DO NOT EDIT.
cask "uuid" do
  version "2.0.0"

  on_macos do
    url "https://github.com/alexrios/uuid/releases/download/v#{version}/uuid_Darwin_all.tar.gz"
    sha256 "2f87a2de30caaa2d229aa0b3185fbd079ff42df1d44f132d105d9d4f19fe7374"
  end

  on_linux do
    on_intel do
      url "https://github.com/alexrios/uuid/releases/download/v#{version}/uuid_Linux_x86_64.tar.gz"
      sha256 "1ff9be64cf8c867c76054bae2424decdcaa4493e16926d8cede955bf4367537a"
    end
    on_arm do
      url "https://github.com/alexrios/uuid/releases/download/v#{version}/uuid_Linux_arm64.tar.gz"
      sha256 "9d17a85b98ed3ef890a6e12010388d5d2b8014a820b3e2fc5ed943f27ce7ad13"
    end
  end

  name "uuid"
  desc "RFC 9562 UUID generator and parser written in Zig"
  homepage "https://github.com/alexrios/uuid"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "uuid"

  # No zap stanza required

end
