# This file was generated by GoReleaser. DO NOT EDIT.
cask "uuid" do
  name "uuid"
  desc "RFC 9562 UUID generator and parser written in Zig"
  homepage "https://github.com/alexrios/uuid"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "uuid"

  on_macos do
    url "https://github.com/alexrios/uuid/releases/download/v#{version}/uuid_Darwin_all.tar.gz"
    sha256 "6fdaffb464f88abf540e5e1b0b2681edf93174f17960bcb008b792836867be7c"
  end

  on_linux do
    on_intel do
      url "https://github.com/alexrios/uuid/releases/download/v#{version}/uuid_Linux_x86_64.tar.gz"
      sha256 "65797b8efc3efaa1c3ed51666bd2d2f13772d7cfac7a54ca973c442f26c020ce"
    end
    on_arm do
      url "https://github.com/alexrios/uuid/releases/download/v#{version}/uuid_Linux_arm64.tar.gz"
      sha256 "108a00128c9044b639b717e6c7257d5ad6f866b19b8eed929ac46c5c0680681e"
    end
  end

  # No zap stanza required
end
