# This file was generated by GoReleaser. DO NOT EDIT.
cask "uuid" do
  name "uuid"
  desc "RFC 9562 UUID generator and parser written in Zig"
  homepage "https://github.com/alexrios/uuid"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "uuid"

  on_macos do
    url "https://github.com/alexrios/uuid/releases/download/v#{version}/uuid_Darwin_all.tar.gz"
    sha256 "589684f443ca17ace9a0921726729e68fb5d66d46145baf0d25506acd4dc8a2e"
  end

  on_linux do
    on_intel do
      url "https://github.com/alexrios/uuid/releases/download/v#{version}/uuid_Linux_x86_64.tar.gz"
      sha256 "b5ea268565f8da64478714738dc074650d6d4b2cc6b9c35e2803921967082640"
    end
    on_arm do
      url "https://github.com/alexrios/uuid/releases/download/v#{version}/uuid_Linux_arm64.tar.gz"
      sha256 "368303e8e7de39dd94d22d12c381280a5ed36f1b0059ef02296d1ae62fbbc171"
    end
  end

  # No zap stanza required
end
